<a href="https://colab.research.google.com/github/kiran-m-kannur/Book-recommendations-for-competitive-exams-using-cosine-similarity-/blob/main/Prediction_With_Cosine_similarity_Short.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#lib
import numpy as np 
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
from google.colab import files
files.upload()

Saving Compi data - Sheet1.csv to Compi data - Sheet1.csv


{'Compi data - Sheet1.csv': b'Title,Genre,Rating,Author,url,Description,Book_id\r\nThe Official Guide to the Revised General Test (2nd Edition),GRE,4.6,McGraw Hill Education,https://m.media-amazon.com/images/I/51ThGwpYoOL._AC_UY218_.jpg,Graduate School Test Preparation,1\r\nManhattan Prep GRE Set of 8 strategy guide (4th Edition),GRE,4.5,Manhattan Prep,https://m.media-amazon.com/images/I/71GPF3vuGwL._AC_UY218_.jpg,Graduate School Test Preparation,2\r\nGRE Big Book,GRE,4.4,ETS,https://m.media-amazon.com/images/I/71HRGPJ56BL._AC_UY218_.gif,Graduate School Test Preparation,3\r\nThe Official GRE Super Power Pack,GRE,4.4,ETS,https://m.media-amazon.com/images/I/61dl09Ww7wL._AC_UY218_.jpg,Graduate School Test Preparation,4\r\nOfficial GRE Verbal Reasoning Practice Questions,GRE,4.4,ETS,https://m.media-amazon.com/images/I/71JkYHYcJdL._AC_UY218_.jpg,Graduate School Test Preparation,5\r\nKaplan\xe2\x80\x99s GRE Premier 2016,GRE,4.4,Kaplan Test Prep,"https://images-na.ssl-images-amazon.com/images

In [ ]:
df = pd.read_csv('/content/Compi data - Sheet1.csv', sep = ',')

In [ ]:
df

Title  ... Book_id
0    The Official Guide to the Revised General Test...  ...       1
1    Manhattan Prep GRE Set of 8 strategy guide (4t...  ...       2
2                                         GRE Big Book  ...       3
3                    The Official GRE Super Power Pack  ...       4
4     Official GRE Verbal Reasoning Practice Questions  ...       5
..                                                 ...  ...     ...
127         Kaplan MCAT Complete 7 Book Subject Review  ...     128
128                 The Princeton Review Complete MCAT  ...     129
129  Examkrackers MCAT complete study package (10th...  ...     130
130  Kaplan Test Prep MCAT 528- Advanced Prep for A...  ...     131
131                  Sterling MCAT Practise Tests 2015  ...     132

[132 rows x 7 columns]

In [ ]:
df.columns

Index(['Title', 'Genre', 'Rating', 'Author', 'url', 'Description', 'Book_id'], dtype='object')

In [ ]:
#change this on google w2v

In [ ]:
columns = ['Title','Authors','Genre']

In [ ]:
def combine_features(data):
  features = []
  for i in range(0, data.shape[0]):
    features.append(data['Title'][i] + ' '+data['Author'][i]+' '+data['Genre'][i])
  return features

In [ ]:
df['combined_features']=combine_features(df)
df.head(50)

Title  ...                                  combined_features
0   The Official Guide to the Revised General Test...  ...  The Official Guide to the Revised General Test...
1   Manhattan Prep GRE Set of 8 strategy guide (4t...  ...  Manhattan Prep GRE Set of 8 strategy guide (4t...
2                                        GRE Big Book  ...                               GRE Big Book ETS GRE
3                   The Official GRE Super Power Pack  ...          The Official GRE Super Power Pack ETS GRE
4    Official GRE Verbal Reasoning Practice Questions  ...  Official GRE Verbal Reasoning Practice Questio...
5                           Kaplan’s GRE Premier 2016  ...     Kaplan’s GRE Premier 2016 Kaplan Test Prep GRE
6   Cracking the GRE Premium Edition 2016 with 6 P...  ...  Cracking the GRE Premium Edition 2016 with 6 P...
7                         Essential Words for the GRE  ...        Essential Words for the GRE Philip Geer GRE
8                                  Barron’s GRE, 2015  ...   Barron’s GRE, 2015 Sharon Weiner Green M.A.  GRE
9                         Nova’s GRE Prep Course Book  ...         Nova’s GRE Prep Course Book Jeff Kolby GRE
10                   Gruber’s Complete GRE Guide 2015  ...  Gruber’s Complete GRE Guide 2015 Gary Gruber  GRE
11          Manhattan GMAT Strategy Guides (10 books)  ...  Manhattan GMAT Strategy Guides (10 books) Manh...
12                 The Official Guide for GMAT Review  ...  The Official Guide for GMAT Review GMAC (Gradu...
13    The Official Guide for GMAT Quantitative Review  ...  The Official Guide for GMAT Quantitative Revie...
14  Kaplan GMAT Prep Plus: 6 Practise Tests + Prov...  ...  Kaplan GMAT Prep Plus: 6 Practise Tests + Prov...
15                        Kaplan GMAT Verbal Workbook  ...  Kaplan GMAT Verbal Workbook Kaplan Test Prep GMAT
16          The Official Guide for GMAT Verbal Review  ...  The Official Guide for GMAT Verbal Review GMAC...
17                          Kaplan GMAT Math Workbook  ...    Kaplan GMAT Math Workbook Kaplan Test Prep GMAT
18                   Official IELTS Practise Material  ...  Official IELTS Practise Material Cambridge ESO...
19              The Official Cambridge Guide to IELTS  ...  The Official Cambridge Guide to IELTS Pauline ...
20                           Barron’s IELTS Superpack  ...  Barron’s IELTS Superpack Lin Lougheed Ph.D. IE...
21  Cambridge English: IELTS 11 Academic with Answers  ...  Cambridge English: IELTS 11 Academic with Answ...
22  Target Band 7: IELTS Academic Module- How to M...  ...  Target Band 7: IELTS Academic Module- How to M...
23                                      Road to IELTS  ...                 Road to IELTS Vinod Gambtoo IELTS 
24                         Kaplan’s TOEFL iBT Premier  ...  Kaplan’s TOEFL iBT Premier Kaplan Test Prep  T...
25                                 Barrons’ TOEFL iBT  ...   Barrons’ TOEFL iBT Pamela J. Sharpe Ph.D. TOEFL 
26  The Official Guide to the TOEFL Test and Offic...  ...  The Official Guide to the TOEFL Test and Offic...
27                    Cambridge Preparation for TOEFL  ...        Cambridge Preparation for TOEFL Gear TOEFL 
28            Princeton Review Cracking the TOEFL iBT  ...  Princeton Review Cracking the TOEFL iBT  PRINC...
29  Data Interpretation & Logical Reasoning by Gau...  ...  Data Interpretation & Logical Reasoning by Gau...
30  Data Interpretation & Data Sufficiency by Anan...  ...  Data Interpretation & Data Sufficiency by Anan...
31  How to Prepare for Data Interpretation for CAT...  ...  How to Prepare for Data Interpretation for CAT...
32  How to Prepare for Verbal Ability and Reading ...  ...  How to Prepare for Verbal Ability and Reading ...
33  How to Prepare for Verbal Ability and Reading ...  ...  How to Prepare for Verbal Ability and Reading ...
34  Logical Reasoning and Data Interpretation for ...  ...  Logical Reasoning and Data Interpretation for ...
35  R.S. Aggarwal’s A Modern Approach to Verbal & ...  ...  R.S. Aggarwal’s A Modern App

In [ ]:
cm = CountVectorizer().fit_transform(df['combined_features'])#matrix converstion
cs = cosine_similarity(cm)#cosine similarity
print(cs)

[[1.         0.23570226 0.18898224 ... 0.07216878 0.0559017  0.06933752]
 [0.23570226 1.         0.35634832 ... 0.06804138 0.21081851 0.13074409]
 [0.18898224 0.35634832 1.         ... 0.         0.         0.        ]
 ...
 [0.07216878 0.06804138 0.         ... 1.         0.25819889 0.32025631]
 [0.0559017  0.21081851 0.         ... 0.25819889 1.         0.43412157]
 [0.06933752 0.13074409 0.         ... 0.32025631 0.43412157 1.        ]]


In [ ]:
Title = df['Title'][43]
Title

'IIT Physics by D.C. Pandey'

In [ ]:
book_id = df[df.Title == Title]['Book_id'].values[0]-1
book_id

43

In [ ]:

scores = list(enumerate(cs[book_id]))
print(scores)

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0890870806374748), (30, 0.07856742013183862), (31, 0.07106690545187014), (32, 0.05986843400892497), (33, 0.05555555555555555), (34, 0.07453559924999298), (35, 0.0), (36, 0.0), (37, 0.0), (38, 0.0890870806374748), (39, 0.25), (40, 0.30151134457776363), (41, 0.31622776601683794), (42, 0.3333333333333333), (43, 1.0), (44, 0.8017837257372732), (45, 0.6666666666666667), (46, 0.22941573387056172), (47, 0.20100756305184242), (48, 0.1781741612749496), (49, 0.2357022603955158), (50, 0.2222222222222222), (51, 0.20100756305184242), (52, 0.19245008972987526), (53, 0.2357022603955158), (54, 0.2357022603955158), (55, 0.15713484026367724), (56, 0.20100756305184242), (57, 0.1490711984999859

In [ ]:
sorted_scores = sorted(scores,key=lambda x:x[1],reverse=True)
sorted_scores = sorted_scores[1:]
sorted_scores

In [ ]:
j=0
print('5 Most recommended books to '+Title+' are:\n')
for item in sorted_scores:
  book_title = df[df.Book_id == item[0]]['Title'].values[0]
  print(j+1,book_title)
  j=j+1
  if j>=5:
    break

5 Most recommended books to IIT Physics by D.C. Pandey are:

1 IIT Physics by D.C. Pandey
2 Fundamentals of Physics by Halliday, Resnick, and Walker
3 Understanding Physics by DC Pandey (Arihant Publications)
4 Calculus – Problems in Calculus of One Variable by I.A. Maron
5 Problems in General Physics by I.E Irodov
